FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY llm_service/requirements.txt .

RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    && pip3 install --no-cache-dir -r ./requirements.txt

COPY llm_service/ /app/llm_service
COPY libs/ /app/libs

ARG TARGET=cuda
COPY llm_service/chatglm_cpp/native/${TARGET}/_C.cpython-310-x86_64-linux-gnu.so \
    /app/llm_service/chatglm_cpp/_C.cpython-310-x86_64-linux-gnu.so

EXPOSE 8001

CMD ["python3", "-m", "llm_service.main"]